image: golang:1.17-alpine

stages:
- test
- build
- deploy

test:
  stage: test
  script:
  - apk add -q --no-cache build-base
  - go test -v ./...

.build:
  stage: build
  script:
  - version="${version}" ./build-releases.sh -e
  artifacts:
    paths:
    - builds/
    expose_as: Binaries

build-latest:
  extends: .build
  before_script:
  - version="latest"
  only:
  - master

build-branch:
  extends: .build
  before_script:
  - version="branch-${CI_COMMIT_REF_SLUG}"
  only:
  - branches
  except:
  - master

build-tag:
  extends: .build
  before_script:
  - version="${CI_COMMIT_TAG}"
  only:
  - tags

deploy-tag:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
  - echo "${CI_COMMIT_TAG}" > builds/VERSION
  - ./deploy-releases.sh -e
  only:
  - tags
