image: golang:1.17

stages:
- test
- build
- deploy

test:
  stage: test
  tags:
  - docker
  before_script:
  - apt-get update -qq && apt-get install -yqq gettext-base && rm -rf /var/lib/apt/lists/*
  script:
  - cat integration-test/config.toml.tpl | envsubst > integration-test/config.toml
  - go test -tags integration -v ./...

.build:
  stage: build
  script:
  - version="${version}" ./build-releases.sh -e
  artifacts:
    paths:
    - builds/
    expose_as: Binaries

build-latest:
  extends: .build
  before_script:
  - major="$(git describe --tags --abbrev=0 | cut -c 2- | cut -d '.' -f 1)"
  - minor="$(git describe --tags --abbrev=0 | cut -c 2- | cut -d '.' -f 2)"
  - version="v${major}.$((${minor:-0}+1)).0-pre+latest"
  only:
  - master

build-branch:
  extends: .build
  before_script:
  - major="$(git describe --tags --abbrev=0 | cut -c 2- | cut -d '.' -f 1)"
  - minor="$(git describe --tags --abbrev=0 | cut -c 2- | cut -d '.' -f 2)"
  - version="v${major}.$((${minor:-0}+1)).0-pre+branch.${CI_COMMIT_REF_SLUG}"
  only:
  - branches
  except:
  - master

build-tag:
  extends: .build
  before_script:
  - version="${CI_COMMIT_TAG}"
  only:
  - tags

deploy-tag:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
  - echo "${CI_COMMIT_TAG}" > builds/VERSION
  - ./deploy-releases.sh -e
  only:
  - tags
