image: golang:1.17-alpine

stages:
- test
- build
- deploy

test:
  stage: test
  script:
  - apk add -q --no-cache build-base
  - go test -v ./...

.build:
  stage: build
  script:
  - apk add -q --no-cache zip
  - version="${version}" ./build-releases.sh -e
  artifacts:
    paths:
    - builds/
    expose_as: Binaries

build-latest:
  extends: .build
  before_script:
  - version="latest"
  only:
  - master

build-branch:
  extends: .build
  before_script:
  - version="branch-${CI_COMMIT_REF_SLUG}"
  only:
  - branches
  except:
  - master

build-tag:
  extends: .build
  before_script:
  - version="${CI_COMMIT_TAG}"
  only:
  - tags

deploy-tag:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
  - echo "${CI_COMMIT_TAG}" > builds/VERSION
  - aws s3 cp builds/VERSION                    s3://polarctl/test/
  - aws s3 cp builds/polarctl-linux-amd64       s3://polarctl/test/ --content-disposition 'attachment; filename="polarctl"'
  - aws s3 cp builds/polarctl-linux-arm64       s3://polarctl/test/ --content-disposition 'attachment; filename="polarctl"'
  - aws s3 cp builds/polarctl-darwin-amd64      s3://polarctl/test/ --content-disposition 'attachment; filename="polarctl"'
  - aws s3 cp builds/polarctl-darwin-arm64      s3://polarctl/test/ --content-disposition 'attachment; filename="polarctl"'
  - aws s3 cp builds/polarctl-windows-amd64.exe s3://polarctl/test/ --content-disposition 'attachment; filename="polarctl.exe"'
  only:
  - tags
